name: build-push-docker-image

on:
  workflow_call:
    inputs:
      dockerhub_username:
        required: true
        type: string
      dockerhub_repository:
        required: true
        type: string
      path_dockerfile:
        required: true
        type: string
        default: Dockerfile
    secrets:
      dokerhub_token:
        required: true

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set current date variable
        id: build_date
        run: echo "BUILD_DATE=$(date +%s)" >> $GITHUB_OUTPUT
      - name: Build the Docker image
        run: docker build . --file ${{ inputs.path_dockerfile }} --tag ${{ vars.DOCKER_HUB_USERNAME}}/${{ inputs.dockerhub_repository }}:${{ steps.build_date.outputs.BUILD_DATE }}
      - name: Push image to Dockerhub
        run: | 
         docker login -u ${{ vars.DOCKER_HUB_USERNAME}} -p ${{ secrets.dokerhub_token }}
         docker push ${{ vars.DOCKER_HUB_USERNAME}}/${{ inputs.dockerhub_repository }}:${{ steps.build_date.outputs.BUILD_DATE }}

         
