name: Docker Image CI

on:
  push:
    paths:
      - 'simple-app-py/Dockerfile'
      - 'simple-app-py/*.py'
      - 'py-challenges/*.py'
  pull_request:
    paths:
      - 'simple-app-py/Dockerfile'
      - 'simple-app-py/*.py'
      - 'py-challenges/*.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set current date variable
      id: build_date
      run: echo "BUILD_DATE=$(date +%s)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file simple-app-py/Dockerfile --tag ${{ vars.DOCKER_HUB_USERNAME}}/simpleapp-py:${{ env.BUILD_DATE }}
    - name: Push image to Dockerhub
      run: | 
       docker login -u ${{ vars.DOCKER_HUB_USERNAME}} -p ${{ secrets.DOCKER_HUB_TOKEN }}
       docker push ${{ vars.DOCKER_HUB_USERNAME}}/simpleapp-py:${{ env.BUILD_DATE }}
    - name: Update docker image tag value in chart helm file
      uses: fjogeleit/yaml-update-action@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        valueFile: 'helm-charts/simpleapp-py/values.yaml'
        propertyPath: 'image.tag'
        value: ${{ env.BUILD_DATE }}
        branch: main
        message: 'Update Image Version to ${{ env.BUILD_DATE }}'

  call-workflow:
    uses: diabloguardian/imp-devops-2026/.github/workflows/scan-w-trivy.yml@main
    with:
      dockerhub_username: ${{ vars.DOCKER_HUB_USERNAME}}
      application_name: 'simpleapp-py'
      tag: ${{ needs.build_date.env.BUILD_DATE }}
    secrets:
      dokerhub_token: ${{ secrets.DOCKER_HUB_TOKEN }}

